### ISSUE TITLE
undefined method `project' for #<Pod::Sandbox:0x00007f9f0c52ac30> Did you mean?  project_path

### ISSUE THREAD

**Issue by sreeharsha999** [Ruenzuo/cocoapods-amimono-example#2]
while running pod install i am getting the following error
[!] An error occurred while processing the post-install hook of the Podfile.

undefined method `project' for #<Pod::Sandbox:0x00007f9f0c52ac30>
Did you mean?  project_path

/Library/Ruby/Gems/2.6.0/gems/cocoapods-amimono-0.0.10/lib/cocoapods-amimono/patcher.rb:47:in `patch_copy_resources_script'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-amimono-0.0.10/lib/cocoapods-amimono/patcher.rb:11:in `patch!'
/Users/sreeharshag/Downloads/cocoapods-amimono-example-master/Podfile:26:in `block (2 levels) in from_ruby'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile.rb:179:in `post_install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:856:in `run_podfile_post_install_hook'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:844:in `block in run_podfile_post_install_hooks'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:145:in `message'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:843:in `run_podfile_post_install_hooks'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:322:in `block in create_and_save_projects'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:303:in `create_and_save_projects'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:294:in `generate_pods_project'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:173:in `integrate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:162:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

**Comment by abhinavroy23** [comment]
Any update on this issue? I am getting the same while installing.

**Comment by liubangde88** [comment]
me too ~
